name: mbarq
channels:
  - bioconda
  - conda-forge
dependencies:
  - mageck
  - python==3.10
  - blast==2.9.*
  - bedtools==2.30.*
  - biopython==1.79
  - numpy
  - pandas
  - pytest
  - click
  - pandera
  - pyranges==0.0.117
  - pybedtools == 0.9.0
  - setuptools<=70
  - pip

